BaseUrl = "https://eng.fieldnation.com/"
LanguageCode = "en-us"
Title = "Engineers @ Field Nation"
Paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2019"
CanonifyURLs = true
ContentDir = "content"
PublishDir = "docs"
PluralizelistTitles = false
Theme = "casper"

[indexes]
  catagory = "catagories"

[params]
  description = "Online Marketplace Software Engineering"
  # cover = "images/cover.jpg"
  author = "Field Nation"
  authorlocation = "Minneapolis, Minnesota"
  authorwebsite = "https://fieldnation.com"
  bio= "Get Work Done with Field Nation"
  logo = "images/logo.png"
  cover = "images/1500x500_cover.jpg"
  googleAnalyticsUserID = "UA-3952637-6"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "fieldnation"
  twitterName = "fieldnation"
  facebookName = "fieldnation"
  # linkedinName = "fieldnation"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  identifier = "blog"
  name = "Engineering Blog"
  url = "/"
  weight = -120
[[menu.main]]
  identifier = "fieldnation"
  name = "Field Nation"
  url = "https://www.fieldnation.com/"
  weight = 100
[[menu.main]]
  name = "Github"
  url = "https://github.com/fieldnation"
  weight = 101
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/fieldnation"
  weight = 102
