BaseUrl = "http://eng.fieldnation.com/"
LanguageCode = "en-us"
Title = "Field Nation"
Paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
CanonifyURLs = true
ContentDir = "content"
PublishDir = "public"
PluralizelistTitles = false
Theme = "casper"

[indexes]
  catagory = "catagories"

[params]
  description = "Find Work. Post Work. Manage Work."
  # cover = "images/cover.jpg"
  author = "Field Nation"
  authorlocation = "Minneapolis, Minnesota"
  authorwebsite = "https://fieldnation.com"
  bio= "Get Work Done with Field Nation"
  logo = "images/logo.png"
  cover = "images/1500x500_cover.jpg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "fieldnation"
  twitterName = "fieldnation"
  facebookName = "fieldnation"
  # linkedinName = "fieldnation"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:slug/"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = -120
[[menu.main]]
  name = "Github"
  pre = "<h3>Find Us On:</h3>"
  url = "https://github.com/fieldnation"
  weight = 100
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/fieldnation"
  weight = 101
